@startuml

title __DATABASE's Class Diagram__\n

  namespace com.example.foodliveryapp {
    namespace database {
      class com.example.foodliveryapp.database.RequestHandler {
          {static} - ctx : Context
          {static} - instance : RequestHandler
          - requestQueue : RequestQueue
          + addToRequestQueue()
          {static} + getInstance()
          + getRequestQueue()
          - RequestHandler()
      }
    }
  }
  

  namespace com.example.foodliveryapp {
    namespace database {
      interface com.example.foodliveryapp.database.ServerCallback {
          {abstract} + onSuccess()
      }
    }
  }
  

  namespace com.example.foodliveryapp {
    namespace database {
      interface com.example.foodliveryapp.database.ServerErrorCallback {
          {abstract} + onFailure()
      }
    }
  }
  

  namespace com.example.foodliveryapp {
    namespace database {
      class com.example.foodliveryapp.database.Services {
          {static} + ACCEPT_ORDER : String
          {static} + CHECK_CODE : String
          {static} + COMPLETED_ORDER : String
          {static} + DELETE_OLD_TIMESTAMPS : String
          {static} + DELIVERED_ORDER : String
          {static} + DELIVER_ORDER : String
          {static} + DENY_ORDER : String
          {static} + DRIVE_COMPLETED_ORDER : String
          {static} + GET_AVAILABILITY_FORM : String
          {static} + GET_DAILY_STATS : String
          {static} + GET_DAILY_TOP_REST : String
          {static} + GET_DETAILED_ORDER : String
          {static} + GET_MONTHLY_STATS : String
          {static} + GET_MONTHLY_TOP_REST : String
          {static} + GET_OPINION_FORM : String
          {static} + GET_ORDERS : String
          {static} + GET_RESTAURANTS : String
          {static} + GET_WORKERS : String
          {static} + LOGIN : String
          {static} + NOT_DELIVERED_ORDER : String
          {static} + REGISTER : String
          {static} + UPDATE_AVAILABILITY_FORM : String
          {static} + UPDATE_LOCATION : String
          {static} + UPDATE_OPINION_FORM : String
          {static} + UPDATE_PASSWORD : String
          {static} + UPDATE_PHONE : String
          {static} + WAIT_REST_ORDER : String
          {static} - SERVER_URL : String
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
